development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 2
  username: demo07
  password: random_pass

production:
  adapter: postgresql
  encoding: unicode
  database: db/production.pg
  pool: 2
  username: demo07
  password: random_pass